## 集成方法
集成方法的目标是将使用给定学习算法构建的几个基本估计量的预测结合起来，以提高单个估计量的通用性/鲁棒性。通常区分两种集成方法：(1)在平均方法中，驱动原理是独立建立多个估计量，然后平均其预测。平均而言，由于组合估计量的方差减小，因此组合估计量通常比任何单个基本估计量都要好。例如： 套袋方法，随机树木森林 …;(2)相比之下，在增强方法中，基础估计器是按顺序构建的，并且人们尝试减小组合估计器的偏差。这样做的动机是结合几个弱模型以产生强大的整体。例如： AdaBoost，梯度树增强 …


### BaggingClassifier
Bagging分类器是一个集合元估计器，它使每个基本分类器适合原始数据集的随机子集，然后将其单个预测（通过投票或平均）进行汇总以形成最终预测。通过将随机化引入其构造过程中，然后使其整体，这种元估计器通常可以用作减少黑匣子估计器（例如决策树）方差的方法。

**参数：**
 - base_estimator:对象，默认=无;基础模型（或称为estimator），默认为None，使用决策树。
 - n_estimators:int，默认= 10;基础模型数量。
 - max_samples:int或float，默认为1.0;用来给每个子模型训练数据集抽取比例。如果是int，则表示数量，如果是float则表示比例。
 - max_features:int或float，默认= 1.0;特征子采样参数，如果是int，则表示数量，如果是float则表示比例。
 - bootstrap:bool，默认为True;采样时是否替换替换，默认执行不替换的采样。
 - bootstrap_features:bool，默认= False;是否替换特征。
 - oob_score: bool，默认= False;是否使用现成的样本来估计泛化误差。
 - warm_start: bool，默认为False;设置为True时，请重用上一个调用的解决方案以适合并为集合添加更多估计量，否则，仅适合一个全新的集合。
 - n_jobs: int，默认=无;使用线程数。-1表示所有，可能会对可视化编程的监控线程造成影响。
 - random_state: int或RandomState，默认=无;随机数种子。
 - verbose: int, 默认为;训练和测试过程展示的详细程度。

In [1]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=100, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)
clf = BaggingClassifier(base_estimator=SVC(),
                        n_estimators=10, random_state=0).fit(X, y)
clf.predict([[0, 0, 0, 0]])

array([1])

### BaggingRegressor
Bagging回归器是一个集合元估计器，它使每个基本回归器适合原始数据集的随机子集，然后将其单个预测（通过投票或平均）进行汇总以形成最终预测。通过将随机化引入其构造过程中，然后使其整体，这种元估计器通常可以用作减少黑盒估计器（例如决策树）方差的方法。

**参数：**
 - base_estimator:对象，默认=无;基础模型（或称为estimator），默认为None，使用决策树。
 - n_estimators:int，默认= 10;基础模型数量
 - max_samples:int或float，默认为1.0;用来给每个子模型训练数据集抽取比例。如果是int，则表示数量，如果是float则表示比例
 - max_features:int或float，默认= 1.0;特征子采样参数，如果是int，则表示数量，如果是float则表示比例
 - bootstrap:bool，默认为True;采样时是否替换替换，默认执行不替换的采样
 - bootstrap_features:bool，默认= False;是否替换特征
 - oob_score: bool，默认= False;是否使用现成的样本来估计泛化误差。
 - warm_start: bool，默认为False;设置为True时，请重用上一个调用的解决方案以适合并为集合添加更多估计量，否则，仅适合一个全新的集合。
 - n_jobs: int，默认=无;使用线程数。-1表示所有，可能会对可视化编程的监控线程造成影响
 - random_state: int或RandomState，默认=无;随机数种子
 - verbose: int, 默认为;训练和测试过程展示的详细程度

In [1]:
from sklearn.svm import SVR
from sklearn.ensemble import BaggingRegressor
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=100, n_features=4,
                       n_informative=2, n_targets=1,
                       random_state=0, shuffle=False)
regr = BaggingRegressor(base_estimator=SVR(),
                        n_estimators=10, random_state=0).fit(X, y)
regr.predict([[0, 0, 0, 0]])

array([-2.87202411])

### 随机森林
#### 随机森林分类器
随机森林是一种元估计量，它适合数据集各个子样本上的许多决策树分类器，并使用平均数来提高预测准确性和控制过度拟合。子样本大小由max_samplesif参数 控制bootstrap=True（默认），否则整个数据集将用于构建每棵树。

**参数：**
 - n_estimators： int，默认= 100;基础模型数量,默认100。
 
 - criterion：{“gini”, “entropy”}, 默认为”gini”;分割判断标准,基尼或者信息熵。
 
 - max_depth:int, 默认为None;树的最大深度,知道所有叶子都是纯净的,或者直到所有叶子都包含至少min_samples_split个样本。
 
 - min_samples_split:int or float, 默认为2;拆分内部节点所需的最少样本数,如果为整数则表示最小样本数,如果为float则表示百分比,ceil(min_samples_split * n_samples)。
 
 - min_samples_leaf:int or float, 默认为1;在叶节点处需要的最小样本数。仅在任何深度的分裂点在min_samples_leaf左分支和右分支中的每个分支上至少留下训练样本时，才考虑。这可能具有平滑模型的效果，尤其是在回归中。如果为整数则表示最小样本数,如果为float则表示百分比ceil(min_samples_leaf*min_samples_leaf)。
 
 - min_weight_fraction_leaf:float, 默认为0.0;在所有叶节点处（所有输入样本）的权重总和中的最小加权分数。如果未提供sample_weight，则样本的权重相等。
 
 - max_features:int, float or {“auto”, “sqrt”, “log2”}, 默认为"auto";寻找最佳分割时要考虑的功能数量：如果为int，则max_features在每个拆分处考虑要素。如果为float，max_features则为小数，并 在每次拆分时考虑要素。int(max_features * n_features)。如果“自动”，则max_features=sqrt(n_features)。如果是“ sqrt”，则max_features=sqrt(n_features)。如果为“ log2”，则为max_features=log2(n_features)。如果没有，则max_features=n_features。注意：直到找到至少一个有效的节点样本分区，分割的搜索才会停止，即使它需要有效检查多个max_features要素也是如此。
 
 - max_leaf_nodes:int, 默认为None;以最佳的方式建立树。最佳节点定义为杂质的相对减少。如果为None，则叶节点数不受限制。
 
 - min_impurity_decrease:float, 默认为0.0;如果节点分裂导致杂质减少大于或等于该值，则该节点将分裂。
 
 - min_impurity_split：float, 默认为None;树木生长尽早停止的阈值。如果节点的杂质高于阈值，则该节点将分裂，否则为叶。将于0.25删除。
 
 - bootstrap:bool，默认为True;采样时是否替换替换，默认执行不替换的采样。
 
 - oob_score: bool，默认= False;是否使用现成的样本来估计泛化误差。
 
 - warm_start: bool，默认为False;设置为True时，请重用上一个调用的解决方案以适合并为集合添加更多估计量，否则，仅适合一个全新的集合。
 
 - n_jobs: int，默认=无;使用线程数。-1表示所有，可能会对可视化编程的监控线程造成影响。
 
 - random_state: int或RandomState，默认=无;随机数种子。
 
 - verbose: int, 默认为;训练和测试过程展示的详细程度。
 
 - class_weight:dict, list of dict or “balanced”, 默认为None。与形式的类有关的权重。“平衡”模式使用y的值来自动调整与输入数据中的类频率成反比的权重，如下所示： n_samples / (n_classes * np.bincount(y))。对于多输出，y的每一列的权重将相乘。请注意，如果指定了sample_weight，则这些权重将与sample_weight（通过fit方法传递）相乘。
 
 - ccp_alpha:non-negative-float, 默认为0.0;用于最小化成本复杂性修剪的复杂性参数。具有最大成本复杂度的子树小于ccp_alpha所选择的子树 。默认情况下，不执行修剪。
 
 - max_samples:int或float，默认为None;如果bootstrap为True，则从X抽取以训练每个基本估计量的样本数。如果为无（默认），则抽取全部样本。如果为int，则抽取该数量(max_samples)的样本。如果为浮点数，则按比例抽取样品。max_samples * X.shape[0]max_samples(0, 1)。
 

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X, y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [7]:
print(clf.predict([[0, 0, 0, 0]]))

[1]


#### ExtraTreesClassifier
参数与随机森林一致,不同之处在于决策树的阈值选择都是随机的,进一步提高了随机性。

In [8]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.datasets import make_classification
X, y = make_classification(n_features=4, random_state=0)
clf = ExtraTreesClassifier(n_estimators=100, random_state=0)
clf.fit(X, y)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=0, verbose=0,
                     warm_start=False)

In [9]:
clf.predict([[0, 0, 0, 0]])

array([1])

#### 随机森林回归
 
 **参数**
 - n_estimators int，默认= 100;基础模型数量,默认100。
 
 - criterion：{“mse”, “friedman_mse”, “mae”}, default=”mse”，分割时的衡量标准。
 
 - max_depth:int, 默认为None;树的最大深度,知道所有叶子都是纯净的,或者直到所有叶子都包含至少min_samples_split个样本。
 
 - min_samples_split:int or float, 默认为2;拆分内部节点所需的最少样本数,如果为整数则表示最小样本数,如果为float则表示百分比,ceil(min_samples_split * n_samples)。
 
 - min_samples_leaf:int or float, 默认为1;在叶节点处需要的最小样本数。仅在任何深度的分裂点在min_samples_leaf左分支和右分支中的每个分支上至少留下训练样本时，才考虑。这可能具有平滑模型的效果，尤其是在回归中。如果为整数则表示最小样本数,如果为float则表示百分比ceil(min_samples_leaf*min_samples_leaf)。
 
 - min_weight_fraction_leaf:float, 默认为0.0;在所有叶节点处（所有输入样本）的权重总和中的最小加权分数。如果未提供sample_weight，则样本的权重相等。
 
 - max_features:int, float or {“auto”, “sqrt”, “log2”}, 默认为"auto";寻找最佳分割时要考虑的功能数量：如果为int，则max_features在每个拆分处考虑要素。如果为float，max_features则为小数，并 在每次拆分时考虑要素。int(max_features * n_features)。如果“自动”，则max_features=n_features。如果是“ sqrt”，则max_features=sqrt(n_features)。如果为“ log2”，则为max_features=log2(n_features)。如果没有，则max_features=n_features。注意：直到找到至少一个有效的节点样本分区，分割的搜索才会停止，即使它需要有效检查多个max_features要素也是如此。
 
 - max_leaf_nodes:int, 默认为None;以最佳的方式建立树。最佳节点定义为杂质的相对减少。如果为None，则叶节点数不受限制。
 
 - min_impurity_decrease:float, 默认为0.0;如果节点分裂导致杂质减少大于或等于该值，则该节点将分裂。
 
 - min_impurity_split：float, 默认为None;树木生长尽早停止的阈值。如果节点的杂质高于阈值，则该节点将分裂，否则为叶。将于0.25删除
 
 - bootstrap:bool，默认为True;采样时是否替换替换，默认执行不替换的采样。
 
 - oob_score: bool，默认= False;是否使用现成的样本来估计泛化误差。
 
 - warm_start: bool，默认为False;设置为True时，请重用上一个调用的解决方案以适合并为集合添加更多估计量，否则，仅适合一个全新的集合。
 
 - n_jobs: int，默认=无;使用线程数。-1表示所有，可能会对可视化编程的监控线程造成影响。
 
 - random_state: int或RandomState，默认=无;随机数种子。
 
 - verbose: int, 默认为;训练和测试过程展示的详细程度。
 
 - max_samples:int或float，默认为None;如果bootstrap为True，则从X抽取以训练每个基本估计量的样本数。如果为无（默认），则抽取全部样本。如果为int，则抽取该数量(max_samples)的样本。如果为浮点数，则按比例抽取样品。max_samples * X.shape[0]max_samples(0, 1)

In [10]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
X, y = make_regression(n_features=4, n_informative=2,
                       random_state=0, shuffle=False)
regr = RandomForestRegressor(max_depth=2, random_state=0)
regr.fit(X, y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=2, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [11]:
print(regr.predict([[0, 0, 0, 0]]))

[-8.32987858]


**极随机树**

此类实现一个元估计器，该估计器可将多个随机决策树（又名额外树或极限树）拟合到数据集的各个子样本上，并使用平均数来提高预测准确性和控制过度拟合。

In [12]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesRegressor
X, y = load_diabetes(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=0)
reg = ExtraTreesRegressor(n_estimators=100, random_state=0).fit(
   X_train, y_train)
reg.score(X_test, y_test)

0.27081747066124695

### AdaBoost分类器。

AdaBoost分类器是一种元估计器，它首先将分类器拟合到原始数据集上，然后将分类器的其他副本拟合到同一数据集上，但是其中，对错误分类的实例的权重进行了调整，以使后续分类器更加关注困难的情况。

**参数**
 - base_estimator:对象，默认=无;基础模型（或称为estimator），默认为None，使用决策树。
 - n_estimators:int，默认= 10;基础模型数量。
 - learning_rate:float, default=1;学习率缩小了每个分类器的贡献,因此学习率和基础模型数量之间需要平衡。
 - algorithm:{‘SAMME’, ‘SAMME.R’}, default=’SAMME.R’;如果为“ SAMME.R”，则使用SAMME.R实际增强算法。 base_estimator必须支持类概率的计算。如果为“ SAMME”，则使用SAMME离散提升算法。SAMME.R算法通常比SAMME收敛更快，从而以更少的提升迭代次数实现了更低的测试误差。
 - random_state: int或RandomState，默认=无;随机数种子。

In [13]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
clf.fit(X, y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=100, random_state=0)

In [14]:
clf.predict([[0, 0, 0, 0]])

array([1])

In [15]:
clf.score(X, y)

0.983

### AdaBoost回归器

AdaBoost回归器是一个元估计器，它首先将回归器拟合到原始数据集上，然后将回归器的其他副本拟合到同一数据集上，但根据当前预测的误差调整实例的权重。因此，随后的回归者更多地关注困难情况。此类实现称为AdaBoost.R2的算法。

**参数:**
 - base_estimator:对象，默认=无;基础模型（或称为estimator），默认为None，使用决策树。
 - n_estimators:int，默认= 50;基础模型数量;
 - learning_rate:float, default=1;学习率缩小了每个分类器的贡献,因此学习率和基础模型数量之间需要平衡
 - loss: {'linear'，'square'，'exponential'}，默认=“ linear”;每次增强迭代后更新权重时使用的损失函数。
 - random_state: int或RandomState，默认=无;随机数种子

In [16]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.datasets import make_regression
X, y = make_regression(n_features=4, n_informative=2,
                       random_state=0, shuffle=False)
regr = AdaBoostRegressor(random_state=0, n_estimators=100)
regr.fit(X, y)

AdaBoostRegressor(base_estimator=None, learning_rate=1.0, loss='linear',
                  n_estimators=100, random_state=0)

In [17]:
regr.predict([[0, 0, 0, 0]])

array([4.79722349])

In [18]:
regr.score(X, y)

0.9771376939813696

### 梯度提升
梯度提升对任意微分损失函数进行增强的一种概括。GBDT是一种准确有效的现成程序，可用于Web搜索排名和生态学等多个领域的回归和分类问题。

#### GradientBoostingClassifier

GB以渐进的阶段方式建立加性模型；它允许优化任意微分损失函数。在每个阶段，n_classes_ 回归树都适合二项式或多项式偏差损失函数的负梯度。二进制分类是一种特殊情况，其中仅诱导单个回归树。

**参数:**
 - loss;{‘deviance’, ‘exponential’}, 默认为’deviance’:损失函数有待优化。“偏差”是指对具有概率输出的分类的偏差（=逻辑回归）。对于损失，“指数”梯度提升可恢复AdaBoost算法。
 
 - learning_rate:float, 默认为0.1:学习率缩小了每棵树的贡献。在learning_rate和n_estimators之间需要权衡。
 
 - n_estimators:int, 默认为100:要执行的提升阶段数。梯度提升对于过度拟合具有相当强的鲁棒性，因此大量的提升阶数通常会带来更好的性能。
 
 - subsample:float, 默认为1.0:样本子采样,用于拟合各个基础学习器的样本比例。如果小于1.0，则将导致随机梯度增强。subsample与参数n_estimators交互。选择会导致方差减少和偏差增加。subsample < 1.0。
 
 - criterion:{‘friedman_mse’, ‘mse’, ‘mae’}, 默认为’friedman_mse’:衡量分割质量的功能。支持的标准是“ friedman_mse”（均方误差）和Friedman的改进评分，“ mse”（均方误差）和“ mae”（均绝对误差）。默认值'friedman_mse'通常是最好的，因为在某些情况下它可以提供更好的近似值。
 
 - min_samples_split:int or float, 默认为2:拆分内部节点所需的最少样本数：如果为int，则认为min_samples_split是最小值。如果为float，min_samples_split则为分数， 是每个拆分的最小样本数。ceil(min_samples_split * n_samples)。
 
 - min_samples_leaf:int or float, 默认为1:在叶节点处需要的最小样本数。仅在任何深度的分裂点在min_samples_leaf左分支和右分支中的每个分支上至少留下训练样本时，才考虑。这可能具有平滑模型的效果，尤其是在回归中。如果为int，则认为min_samples_leaf是最小值。如果为float，min_samples_leaf则为分数， 是每个节点的最小样本数。ceil(min_samples_leaf * n_samples)。
 
 - min_weight_fraction_leaf:float, 默认为0.0;在所有叶节点处（所有输入样本）的权重总和中的最小加权分数。如果未提供sample_weight，则样本的权重相等。
 
 - max_depth:int, 默认为3:各个决策树的最大深度。最大深度限制了树中节点的数量。调整此参数以获得最佳性能；最佳值取决于各个参数的相互作用。
 - min_impurity_decrease:float, 默认为0.0:如果节点分裂导致杂质减少大于或等于该值，则该节点将分裂。
 
 - min_impurity_split:float, 默认为None:树木生长尽早停止的阈值。如果节点的杂质高于阈值，则该节点将分裂，否则为叶。将于0.25删除。
 
 - init:estimator or ‘zero’, 默认为None:一个估计器对象，用于计算初始预测。 init必须提供fit和predict_proba。如果为“零”，则初始原始预测设置为零。默认情况下，使用 DummyEstimator预测类优先级。
 
 - random_state:int or RandomState, 默认为None:随机数种子。
 
 - max_features:{‘auto’, ‘sqrt’, ‘log2’}, int or float, 默认为None:寻找最佳分割时要考虑的功能数量：如果为int，则max_features在每个拆分处考虑要素。如果为float，max_features则为小数，并 在每次拆分时考虑要素。int(max_features * n_features)。如果为“自动”，则为max_features=sqrt(n_features)。如果为“ sqrt”，则为max_features=sqrt(n_features)。如果为“ log2”，则为max_features=log2(n_features)。如果没有，则max_features=n_features。选择会导致方差减少和偏差增加。max_features < n_features。注意：直到找到至少一个有效的节点样本分区，分割的搜索才会停止，即使它需要有效检查多个max_features要素也是如此。
 
 - verbose:int, 默认为0:启用详细输出。如果为1，则偶尔打印一次进度和性能（树越多，频率越低）。如果大于1，则将打印每棵树的进度和性能。
 
 - max_leaf_nodes:bool, 默认为False;以最好的方式种植树木。最佳节点定义为杂质的相对减少。如果为None，则叶节点数不受限制。
 
 - warm_start bool，默认为False;设置True为时，请重用上一个调用的解决方案以适应并在集合中添加更多的估计量，否则，只需擦除上一个解决方案即可。
 
 - presortde:precated, 默认为’deprecated’;此参数已弃用，并将在v0.24中删除。
 
 - validation_fraction:float, 默认为0.1;预留的训练数据比例作为早期停止的验证集。必须在0到1之间。仅当n_iter_no_change设置为整数时使用。
 
 - n_iter_no_change:int, 默认为None;n_iter_no_change用于确定在验证分数没有改善时是否将使用早期停止来终止训练。默认情况下，将其设置为“无”以禁用提前停止。如果设置为数字，则它将保留validation_fraction训练数据的大小作为验证，并在先前所有n_iter_no_change迭代次数中的验证得分均未提高时终止训练。拆分已分层。
 
 - tol:float, 默认为1e-4;早停阈值。当损失至少不能改善n_iter_no_change迭代次数（如果设置为数字）时，训练将停止。
 
 - ccp_alpha:non-negative float, 默认为0.0;用于最小化成本复杂性修剪的复杂性参数。具有最大成本复杂度的子树小于ccp_alpha所选择的子树 。默认情况下，不执行修剪。

In [1]:
from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
X, y = make_classification(random_state=0)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=0)
clf = GradientBoostingClassifier(random_state=0)
clf.fit(X_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [2]:
clf.predict(X_test[:2])

array([1, 0])

In [3]:
clf.score(X_test, y_test)

0.92

#### GradientBoostingRegressor
GB以渐进的阶段方式建立加性模型；它允许优化任意微分损失函数。在每个阶段，将回归树拟合到给定损失函数的负梯度上。

**参数:**
 - loss;{'ls'，'lad'，'huber'，'quantile'}，默认='ls';损失函数有待优化。“ ls”是指最小二乘回归。“ lad”（最小绝对偏差）是仅基于输入变量的顺序信息的高度鲁棒的损失函数。“ huber”是两者的结合。“分位数”允许分位数回归（用于alpha指定分位数）。
 
 - learning_rate:float, 默认为0.1:学习率缩小了每棵树的贡献。在learning_rate和n_estimators之间需要权衡。
 
 - n_estimators:int, 默认为100:要执行的提升阶段数。梯度提升对于过度拟合具有相当强的鲁棒性，因此大量的提升阶数通常会带来更好的性能。
 
 - subsample:float, 默认为1.0:样本子采样,用于拟合各个基础学习器的样本比例。如果小于1.0，则将导致随机梯度增强。subsample与参数n_estimators交互。选择会导致方差减少和偏差增加。subsample < 1.0。
 
 - criterion:{‘friedman_mse’, ‘mse’, ‘mae’}, 默认为’friedman_mse’:衡量分割质量的功能。支持的标准是“ friedman_mse”（均方误差）和Friedman的改进评分，“ mse”（均方误差）和“ mae”（均绝对误差）。默认值'friedman_mse'通常是最好的，因为在某些情况下它可以提供更好的近似值。
 
 - min_samples_split:int or float, 默认为2:拆分内部节点所需的最少样本数：如果为int，则认为min_samples_split是最小值。如果为float，min_samples_split则为分数， 是每个拆分的最小样本数。ceil(min_samples_split * n_samples)。
 
 - min_samples_leaf:int or float, 默认为1:在叶节点处需要的最小样本数。仅在任何深度的分裂点在min_samples_leaf左分支和右分支中的每个分支上至少留下训练样本时，才考虑。这可能具有平滑模型的效果，尤其是在回归中。如果为int，则认为min_samples_leaf是最小值。如果为float，min_samples_leaf则为分数， 是每个节点的最小样本数。ceil(min_samples_leaf * n_samples)。
 
 - min_weight_fraction_leaf:float, 默认为0.0:在所有叶节点处（所有输入样本）的权重总和中的最小加权分数。如果未提供sample_weight，则样本的权重相等。
 - max_depth:int, 默认为3:各个决策树的最大深度。最大深度限制了树中节点的数量。调整此参数以获得最佳性能；最佳值取决于各个参数的相互作用。
 - min_impurity_decrease:float, 默认为0.0:如果节点分裂导致杂质减少大于或等于该值，则该节点将分裂。
 
 - min_impurity_split:float, 默认为None:树木生长尽早停止的阈值。如果节点的杂质高于阈值，则该节点将分裂，否则为叶。将于0.25删除。
 
 - init:estimator or ‘zero’, 默认为None:一个估计器对象，用于计算初始预测。 init必须提供fit和predict_proba。如果为“零”，则初始原始预测设置为零。默认情况下，使用 DummyEstimator预测类优先级。
 
 - random_state:int or RandomState, 默认为None:随机数种子。
 
 - max_features:{‘auto’, ‘sqrt’, ‘log2’}, int or float, 默认为None:寻找最佳分割时要考虑的功能数量：如果为int，则max_features在每个拆分处考虑要素。如果为float，max_features则为小数，并 在每次拆分时考虑要素。int(max_features * n_features)。如果为“自动”，则为max_features=sqrt(n_features)。如果为“ sqrt”，则为max_features=sqrt(n_features)。如果为“ log2”，则为max_features=log2(n_features)。如果没有，则max_features=n_features。选择会导致方差减少和偏差增加。max_features < n_features。注意：直到找到至少一个有效的节点样本分区，分割的搜索才会停止，即使它需要有效检查多个max_features要素也是如此。
 
 - alphafloat, default=0.9;Huber损失函数和分位数损失函数的alpha分位数。仅当loss='huber'或时loss='quantile'。
 
 - verbose:int, 默认为0:启用详细输出。如果为1，则偶尔打印一次进度和性能（树越多，频率越低）。如果大于1，则将打印每棵树的进度和性能。
 
 - max_leaf_nodes:bool, 默认为False;以最好的方式种植树木。最佳节点定义为杂质的相对减少。如果为None，则叶节点数不受限制。
 
 - warm_start bool，默认为False;设置True为时，请重用上一个调用的解决方案以适应并在集合中添加更多的估计量，否则，只需擦除上一个解决方案即可。
 - presortde:precated, 默认为’deprecated’;此参数已弃用，并将在v0.24中删除。
 
 - validation_fraction:float, 默认为0.1;预留的训练数据比例作为早期停止的验证集。必须在0到1之间。仅当n_iter_no_change设置为整数时使用。
 
 - n_iter_no_change:int, 默认为None;n_iter_no_change用于确定在验证分数没有改善时是否将使用早期停止来终止训练。默认情况下，将其设置为“无”以禁用提前停止。如果设置为数字，则它将保留validation_fraction训练数据的大小作为验证，并在先前所有n_iter_no_change迭代次数中的验证得分均未提高时终止训练。拆分已分层。
 
 - tol:float, 默认为1e-4;早停阈值。当损失至少不能改善n_iter_no_change迭代次数（如果设置为数字）时，训练将停止。
 
 - ccp_alpha:non-negative float, 默认为0.0;用于最小化成本复杂性修剪的复杂性参数。具有最大成本复杂度的子树小于ccp_alpha所选择的子树 。默认情况下，不执行修剪。

In [10]:
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
X, y = make_regression(random_state=0)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=0)
reg = GradientBoostingRegressor(random_state=0)
reg.fit(X_train, y_train)

GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=0, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [11]:
reg.predict(X_test[1:2])

array([-61.05212593])

In [12]:
reg.score(X_test, y_test)

0.43848663277068134