In [1]:
%matplotlib inline
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

## 交叉验证迭代器
#### KFlod
KFlod :交叉切分,将数据分成K份,通过参数n_splits,控制

In [37]:
from sklearn.model_selection import KFold
X = ["a", "b", "c", "d"]
kf = KFold(n_splits=4)
for train, test in kf.split(X):
    print("%s %s" % (train, test))

[1 2 3] [0]
[0 2 3] [1]
[0 1 3] [2]
[0 1 2] [3]


#### RepeateKFlod 重复性KFlod

**重复KFlod函数数次,使用超参数n_repeats进行控制**

In [3]:
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
random_state = 12883823
rkf = RepeatedKFold(n_splits=2, n_repeats=2, random_state=random_state) 
for train, test in rkf.split(X):
    print("%s %s" % (train, test))

[2 3] [0 1]
[0 1] [2 3]
[0 2] [1 3]
[1 3] [0 2]


## 分层交叉切分
**Stratified k-fold:实现了分层交叉切分**

In [29]:
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2, 3, 4],
              [11, 12, 13, 14],
              [21, 22, 23, 24],
              [31, 32, 33, 34],
              [41, 42, 43, 44],
              [51, 52, 53, 54],
              [61, 62, 63, 64],
              [71, 72, 73, 74]])

y = np.array([1, 1, 0, 0, 1, 1, 0, 0])

stratified_folder = StratifiedKFold(n_splits=4, random_state=0, shuffle=False)
for train_index, test_index in stratified_folder.split(X, y):
    print("Stratified Train Index:", train_index)
    print("Stratified Test Index:", test_index)
    print("Stratified y_train:", y[train_index])
    print("Stratified y_test:", y[test_index],'\n')

Stratified Train Index: [1 3 4 5 6 7]
Stratified Test Index: [0 2]
Stratified y_train: [1 0 1 1 0 0]
Stratified y_test: [1 0] 

Stratified Train Index: [0 2 4 5 6 7]
Stratified Test Index: [1 3]
Stratified y_train: [1 0 1 1 0 0]
Stratified y_test: [1 0] 

Stratified Train Index: [0 1 2 3 5 7]
Stratified Test Index: [4 6]
Stratified y_train: [1 1 0 0 1 0]
Stratified y_test: [1 0] 

Stratified Train Index: [0 1 2 3 4 6]
Stratified Test Index: [5 7]
Stratified y_train: [1 1 0 0 1 0]
Stratified y_test: [1 0] 



In [47]:
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2, 3, 4],
              [11, 12, 13, 14],
              [21, 22, 23, 24],
              [31, 32, 33, 34],
              [41, 42, 43, 44],
              [51, 52, 53, 54],
              [61, 62, 63, 64],
              [71, 72, 73, 74]])

y = np.array([1, 1, 0, 0, 1, 1, 0, 0])

stratified_folder = StratifiedKFold(n_splits=4, random_state=0, shuffle=False)
for train_index, test_index in stratified_folder.split(X, y):
    print("Stratified Train Index:", train_index)
    print("Stratified Test Index:", test_index)
    print("Stratified y_train:", y[train_index])
    print("Stratified y_test:", y[test_index],'\n')

Stratified Train Index: [1 3 4 5 6 7]
Stratified Test Index: [0 2]
Stratified y_train: [1 0 1 1 0 0]
Stratified y_test: [1 0] 

Stratified Train Index: [0 2 4 5 6 7]
Stratified Test Index: [1 3]
Stratified y_train: [1 0 1 1 0 0]
Stratified y_test: [1 0] 

Stratified Train Index: [0 1 2 3 5 7]
Stratified Test Index: [4 6]
Stratified y_train: [1 1 0 0 1 0]
Stratified y_test: [1 0] 

Stratified Train Index: [0 1 2 3 4 6]
Stratified Test Index: [5 7]
Stratified y_train: [1 1 0 0 1 0]
Stratified y_test: [1 0] 



**后面的代码则很好的对他们的不同进行了对比**

**除了这几种交叉切分KFlod外,还有很多其他的分割方式,比如`StratifiedShuffleSplit`重复分层KFold,实现了每个K中各类别的比例与原数据集大致一致,而`RepeatedStratifiedKFold` 可用于在每次重复中用不同的随机化重复分层 K-Fold n 次。至此基本的KFlod在Sklearn中都实现了**

**注意**

而 i.i.d 数据是机器学习理论中的一个常见假设，在实践中很少成立。如果知道样本是使用时间相关的过程生成的，则使用 time-series aware cross-validation scheme 更安全。 同样，如果我们知道生成过程具有 group structure （群体结构）（从不同 subjects（主体） ， experiments（实验）， measurement devices （测量设备）收集的样本），则使用 group-wise cross-validation 更安全。

下面就是一个分组KFold的例子,分组KFold将会使用我们给予的groups(组)进行分层抽样.在一些特殊情况下,我们可能会使用到这个.

In [24]:
from sklearn.model_selection import GroupKFold

X = np.array([0.1, 0.2, 2.2, 2.4, 2.3, 4.55, 5.8, 8.8, 9, 10])
y = np.array(["a", "b", "b", "b", "c", "c", "c", "d", "d", "d"])
groups = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3])

gkf = GroupKFold(n_splits=3)
for train, test in gkf.split(X, y, groups=groups):
    print("%s %s" % (train, test))

[0 1 2 3 4 5] [6 7 8 9]
[0 1 2 6 7 8 9] [3 4 5]
[3 4 5 6 7 8 9] [0 1 2]


更多内容请参考:[sklearn相应手册](http://scikit-learn.org/stable/modules/cross_validation.html)

In [25]:
kFlod_folder = KFold(n_splits=4, random_state=0, shuffle=False)
for train_index, test_index in kFlod_folder.split(X, y):
    print("KFold Train Index:", train_index)
    print("KFold Test Index:", test_index)
    print("KFold y_train:", groups[train_index])
    print("KFold y_test:", groups[test_index],'\n')

KFold Train Index: [3 4 5 6 7 8 9]
KFold Test Index: [0 1 2]
KFold y_train: [2 2 2 3 3 3 3]
KFold y_test: [1 1 1] 

KFold Train Index: [0 1 2 6 7 8 9]
KFold Test Index: [3 4 5]
KFold y_train: [1 1 1 3 3 3 3]
KFold y_test: [2 2 2] 

KFold Train Index: [0 1 2 3 4 5 8 9]
KFold Test Index: [6 7]
KFold y_train: [1 1 1 2 2 2 3 3]
KFold y_test: [3 3] 

KFold Train Index: [0 1 2 3 4 5 6 7]
KFold Test Index: [8 9]
KFold y_train: [1 1 1 2 2 2 3 3]
KFold y_test: [3 3] 



In [27]:
repeated_folder = RepeatedKFold(n_splits=4, n_repeats = 2 ,random_state=0)
for train_index, test_index in repeated_folder.split(X, y):
    print("RepeatedKFold Train Index:", train_index)
    print("RepeatedKFold Test Index:", test_index)
    print("KFold y_train:", groups[train_index])
    print("KFold y_test:", groups[test_index],'\n')

RepeatedKFold Train Index: [0 1 3 5 6 7 9]
RepeatedKFold Test Index: [2 4 8]
KFold y_train: [1 1 2 2 3 3 3]
KFold y_test: [1 2 3] 

RepeatedKFold Train Index: [0 2 3 4 5 7 8]
RepeatedKFold Test Index: [1 6 9]
KFold y_train: [1 1 2 2 2 3 3]
KFold y_test: [1 3 3] 

RepeatedKFold Train Index: [0 1 2 4 5 6 8 9]
RepeatedKFold Test Index: [3 7]
KFold y_train: [1 1 1 2 2 3 3 3]
KFold y_test: [2 3] 

RepeatedKFold Train Index: [1 2 3 4 6 7 8 9]
RepeatedKFold Test Index: [0 5]
KFold y_train: [1 1 2 2 3 3 3 3]
KFold y_test: [1 2] 

RepeatedKFold Train Index: [0 2 4 6 7 8 9]
RepeatedKFold Test Index: [1 3 5]
KFold y_train: [1 1 2 3 3 3 3]
KFold y_test: [1 2 2] 

RepeatedKFold Train Index: [0 1 3 4 5 6 7]
RepeatedKFold Test Index: [2 8 9]
KFold y_train: [1 1 2 2 2 3 3]
KFold y_test: [1 3 3] 

RepeatedKFold Train Index: [1 2 3 4 5 7 8 9]
RepeatedKFold Test Index: [0 6]
KFold y_train: [1 1 2 2 2 3 3 3]
KFold y_test: [1 3] 

RepeatedKFold Train Index: [0 1 2 3 5 6 8 9]
RepeatedKFold Test Index: [4 7]