### LabelBinarizer
以一对一的方式对标签进行二值化
**参数:**
 - neg_label:int,默认0;负标签必须编码的值
 - pos_label:int,默认0;正标签必须编码的值
 - sparse_output:稀疏输出,布尔,默认False;如果希望从转换返回的数组为稀疏CSR格式,则为true

In [1]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit([1, 2, 6, 4, 2])

LabelBinarizer()

In [2]:
lb.classes_

array([1, 2, 4, 6])

In [3]:
lb.transform([1, 6])

array([[1, 0, 0, 0],
       [0, 0, 0, 1]])

In [4]:
lb = preprocessing.LabelBinarizer()
lb.fit_transform(['yes', 'no', 'no', 'yes'])

array([[1],
       [0],
       [0],
       [1]])

In [5]:
import numpy as np
lb.fit(np.array([[0, 1, 1], [1, 0, 0]]))

LabelBinarizer()

In [6]:
lb.classes_

array([0, 1, 2])

In [7]:
lb.transform([0, 1, 2, 1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0]])

### LabelEncoder
使用0到n_classes-1之间的值编码目标标签。该转换器应用于编码目标值，即 y，而不是输入X。

**参数:**
 - 无

LabelEncoder 可以用来规范标签。

In [8]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit([1, 2, 2, 6])

LabelEncoder()

In [9]:
le.classes_

array([1, 2, 6])

In [10]:
le.transform([1, 1, 2, 6])

array([0, 0, 1, 2])

In [11]:
le.inverse_transform([0, 0, 1, 2])

array([1, 1, 2, 6])

它也可以用于将非数字标签（只要它们是可哈希的和可比较的）转换为数字标签。

In [12]:
le = preprocessing.LabelEncoder()
le.fit(["paris", "paris", "tokyo", "amsterdam"])

list(le.classes_)

['amsterdam', 'paris', 'tokyo']

In [13]:
le.transform(["tokyo", "tokyo", "paris"])

array([2, 2, 1])

In [14]:
list(le.inverse_transform([2, 2, 1]))

['tokyo', 'tokyo', 'paris']